trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: GoTool@0
    inputs:
      version: "1.13.5"

  - script: go test -v ./...
    workingDirectory: "$(modulePath)"
    displayName: "Run tests"
